### ISSUE TITLE
회원가입 - 회원가입 기본 구조 생성

### ISSUE THREAD

**Issue by Stilllee** [LAB13-REACT-TAING/LAB13-PROJECT#66]
![Image](https://user-images.githubusercontent.com/108785772/224550288-900cbf7c-7115-451e-a3d5-b05543e05e62.png)
만족 -> '영문 소문자 또는 영문 소문자, 숫자 조합 6~12 자리'

![image](https://user-images.githubusercontent.com/108785772/224549854-66ee6d1f-9bdc-487c-b105-d03725680a91.png)
경고문구 : '영문 소문자 또는 영문 소문자, 숫자 조합 6~12 자리로 입력해주세요' 
- 한글
- 특수문자
- 2자리 미만
- 12자리 초과

**Comment by luckydoyun** [comment]
firebase 에서 아이디/비밀번호 인증을 제공하지 않으므로 아이디 기능 구현 삭제
